### ISSUE TITLE
ReactとRailsAPIモードで開発する

### ISSUE THREAD

**Issue by naorespawn** [naorespawn/PokemonBattleCalculator#25]
RailsメインでGemとしてReactを使用するよりかは
実践的な内容なのでは？

* [ReactをRailsと共に使う方法 - Qiita](https://qiita.com/k-penguin-sato/items/e3cc04f787cf3254cfae)
* [K-Sato1995/Rails_React_GraphQL_Docker_Boilerplate: Rails + React + GraphQL + Docker🤡🤡](https://github.com/K-Sato1995/Rails_React_GraphQL_Docker_Boilerplate)
* [【Rails】graphql-rubyでAPIを作成 - Qiita](https://qiita.com/k-penguin-sato/items/07fef2f26fd6339e0e69)
* [Railsで超簡単API - Qiita](https://qiita.com/k-penguin-sato/items/adba7a1a1ecc3582a9c9#%E5%8F%82%E8%80%83)
* [「GraphQL」徹底入門 ─ RESTとの比較、API・フロント双方の実装から学ぶ ](https://employment.en-japan.com/engineerhub/entry/2018/12/26/103000)
* [Reactの開発環境をDockerで構築してみた | ニフティものづくりブログ](https://blog.web.nifty.com/engineer/2714)
* [Rails APIモード + Reactに入門してみる - yikegaya’s blog](https://ikeyu0806.hatenablog.com/entry/2019/05/05/113153)
* [RailsのDockerイメージを一番小さくする方法 - Qiita](https://qiita.com/baban/items/99877f9b3065c4cf3d50)

**Comment by muitimon** [comment]
https://note.com/tsuchi_13/n/n8ba2dd21ea37

**Comment by muitimon** [comment]
[Tutorial: Intro to React](https://reactjs.org/tutorial/tutorial.html)をやってみる

**Comment by naorespawn** [comment]
## 使用予定
* Rails (API)
* Docker
* React
* MySQL
* GraphQL

## 大まかな工程
1. React用Dockerfile, Rails用Dockerfile, Gemfile, Gemfile.lock, dockercompose.ymlを用意
2. Rails側で`rails new -api` 実行

**Comment by naorespawn** [comment]
# ライブラリ詳細
```dockerfile
RUN apk add --update --no-cache --virtual=builders \
      alpine-sdk build-base linux-headers ruby-dev zlib-dev postgresql-dev
RUN apk add --update --no-cache \
      libc6-compat libc-dev zlib ruby-json tzdata yaml less curl postgresql
```

* alpine-adk
* build-base
* linux-headers
* ruby-dev
* zlib-dev
* postgresql-dev

* libc6-compat
* libc-dev
* zlib
* ruby-json
* tzdata
* yaml
* less
* curl
* postgresql

**Comment by naorespawn** [comment]
[Boilerplateからコピー · naorespawn/PokemonBattleCalculator@08f6f54](https://github.com/naorespawn/PokemonBattleCalculator/commit/08f6f54cf5a0fedf8fb3b824bd7e2afd5a4e9ccc)
にて解決したのでclose

#25 fix とコミットメッセージを入れると自動でclose出来たようだ

masterへmergeする際にはPull Request経由でMergeするべきであった
