### ISSUE TITLE
SwaggerでAPIの仕様をまとめる

### ISSUE THREAD

**Issue by muitimon** [naorespawn/PokemonBattleCalculator#26]
# 概要
API設計を考えていないので、まだ曖昧だがとりあえず考えるばを作った

# 目的

# 提案内容
API設計で使うツールなどを考えたい

# タスク
- [x] 細かいタスクに分解できているなら書き出す

**Comment by muitimon** [comment]
[API 記述言語や API ドキュメンテーションツールの比較（Swagger、API Blueprint、RAML）](https://qiita.com/tetsukamp/items/a05f40fcab6d528b1e4f)

[swagger](https://swagger.io/)を使いたい

**Comment by naorespawn** [comment]
## エディタ
* [本当に使ってよかったOpenAPI (Swagger) ツール | フューチャー技術ブログ](https://future-architect.github.io/articles/20191008/)

SwaggerのサードパーティGUIエディタ Stoplight Studioを使う

## API仕様
* [APIs Dashboard | ProgrammableWeb](https://www.programmableweb.com/apis)
* [RESTful APIのURI設計(エンドポイント設計) - Qiita](https://qiita.com/NagaokaKenichi/items/6298eb8960570c7ad2e9)
* [Qiita API v2ドキュメント - Qiita:Developer](https://qiita.com/api/v2/docs)

記事を参考に仕様を詰める

**Comment by naorespawn** [comment]
[すばらしきポケモンエコシステム⚡️ - Qiita](https://qiita.com/seya/items/47dc0ebae55674d8902f)
[PokéAPI](https://pokeapi.co/)そもそもAPI自前設計しなくとも良いのでは

**Comment by naorespawn** [comment]
* [Documentation - PokéAPI](https://pokeapi.co/docs/v2)
* [rdavid1099/poke-api-v2: Ruby gem wrapper for https://pokeapi.co/api/v2/](https://github.com/rdavid1099/poke-api-v2)

Gemもあるのでこちらを使用する
